language: node_js

node_js:
  - "7"

cache:
  directories:
    - node_modules

before_install:
  - npm install codecov blanket mocha-lcov-reporter

script:
  - npm build
  - npm test
  - SMITTY_COVERAGE=1 ./node_modules/.bin/mocha \
      --require blanket \
      --reporter mocha-lcov-reporter
    codecov

cache:
  directories:
    - node_modules
